"""initial schema

Hand-written to mirror ``qjsync.state.models`` exactly: four tables
(``sync_runs``, ``detection_state``, ``kb_cache``, ``jobs``) plus the four enum
types. JSON columns use ``sa.JSON`` (portable; becomes JSONB on PostgreSQL via the
model's ``with_variant``). Keeping it hand-written keeps the enum/JSON intent
explicit and reviewable rather than autogenerated.

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-19
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


# Enum types, named to match the SAEnum(..., name=...) in state/models.py.
# The labels are the Python enum MEMBER NAMES, which is what SQLAlchemy's default (no
# values_callable) Enum persists and what `init-db`/create_all builds from the ORM models.
# Keeping them in lock-step is what lets `alembic upgrade head` produce a schema the ORM can
# actually write to — an earlier lowercase-value version rejected the ORM's name-based inserts
# (e.g. invalid input value for enum sync_run_status: "RUNNING").
sync_run_status = sa.Enum("RUNNING", "SUCCESS", "FAILED", name="sync_run_status")
sync_mode = sa.Enum("INCREMENTAL", "FULL", name="sync_mode")
closure_reason = sa.Enum("FIXED", "STALE", name="closure_reason")
job_status = sa.Enum("PENDING", "IN_PROGRESS", "DONE", "FAILED", name="job_status")


def upgrade() -> None:
    op.create_table(
        "sync_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sync_run_status, nullable=False),
        sa.Column("mode", sync_mode, nullable=False),
        sa.Column("evaluated", sa.Integer(), nullable=False),
        sa.Column("created", sa.Integer(), nullable=False),
        sa.Column("updated", sa.Integer(), nullable=False),
        sa.Column("closed_fixed", sa.Integer(), nullable=False),
        sa.Column("marked_stale", sa.Integer(), nullable=False),
        sa.Column("reopened", sa.Integer(), nullable=False),
        sa.Column("skipped", sa.Integer(), nullable=False),
        sa.Column("notes", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_sync_runs_mode", "sync_runs", ["mode"], unique=False)

    op.create_table(
        "detection_state",
        sa.Column("primary_key", sa.String(length=255), nullable=False),
        sa.Column("host_id", sa.BigInteger(), nullable=False),
        sa.Column("qid", sa.Integer(), nullable=False),
        sa.Column("port", sa.String(length=32), nullable=False),
        sa.Column("unique_vuln_id", sa.BigInteger(), nullable=True),
        sa.Column("jira_issue_key", sa.String(length=64), nullable=True),
        sa.Column("jira_status", sa.String(length=128), nullable=True),
        sa.Column("jira_resolution", sa.String(length=128), nullable=True),
        sa.Column("qualys_status", sa.String(length=32), nullable=True),
        sa.Column("tracking_method", sa.String(length=32), nullable=True),
        sa.Column("last_vm_scanned_date", sa.String(length=32), nullable=True),
        sa.Column("material_hash", sa.String(length=64), nullable=True),
        sa.Column("signals", sa.JSON(), nullable=True),
        sa.Column("first_seen_run", sa.BigInteger(), nullable=True),
        sa.Column("last_seen_run", sa.BigInteger(), nullable=True),
        sa.Column("consecutive_misses", sa.Integer(), nullable=False),
        sa.Column("issue_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_reason", closure_reason, nullable=True),
        sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sticky", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("primary_key"),
    )
    op.create_index(
        "ix_detection_state_host_id", "detection_state", ["host_id"], unique=False
    )
    op.create_index("ix_detection_state_qid", "detection_state", ["qid"], unique=False)
    op.create_index(
        "ix_detection_state_jira_issue_key",
        "detection_state",
        ["jira_issue_key"],
        unique=False,
    )
    op.create_index(
        "ix_detection_state_last_seen_run",
        "detection_state",
        ["last_seen_run"],
        unique=False,
    )
    op.create_index(
        "ix_detection_state_open",
        "detection_state",
        ["jira_issue_key", "closed_at"],
        unique=False,
    )

    op.create_table(
        "kb_cache",
        sa.Column("qid", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=255), nullable=True),
        sa.Column("severity_level", sa.Integer(), nullable=True),
        sa.Column("vuln_type", sa.String(length=64), nullable=True),
        sa.Column("patchable", sa.Boolean(), nullable=True),
        sa.Column("pci_flag", sa.Boolean(), nullable=True),
        sa.Column("cvss_base", sa.Float(), nullable=True),
        sa.Column("cvss_temporal", sa.Float(), nullable=True),
        sa.Column("cvss_v3_base", sa.Float(), nullable=True),
        sa.Column("cvss_v3_temporal", sa.Float(), nullable=True),
        sa.Column("published_datetime", sa.String(length=32), nullable=True),
        sa.Column(
            "last_service_modification_datetime", sa.String(length=32), nullable=True
        ),
        sa.Column("diagnosis", sa.Text(), nullable=True),
        sa.Column("consequence", sa.Text(), nullable=True),
        sa.Column("solution", sa.Text(), nullable=True),
        sa.Column("cve_list", sa.JSON(), nullable=True),
        sa.Column("rtis", sa.JSON(), nullable=True),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("qid"),
    )

    op.create_table(
        "jobs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", job_status, nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_jobs_run_id", "jobs", ["run_id"], unique=False)
    op.create_index("ix_jobs_status", "jobs", ["status"], unique=False)


def downgrade() -> None:
    op.drop_index("ix_jobs_status", table_name="jobs")
    op.drop_index("ix_jobs_run_id", table_name="jobs")
    op.drop_table("jobs")

    op.drop_table("kb_cache")

    op.drop_index("ix_detection_state_open", table_name="detection_state")
    op.drop_index("ix_detection_state_last_seen_run", table_name="detection_state")
    op.drop_index("ix_detection_state_jira_issue_key", table_name="detection_state")
    op.drop_index("ix_detection_state_qid", table_name="detection_state")
    op.drop_index("ix_detection_state_host_id", table_name="detection_state")
    op.drop_table("detection_state")

    op.drop_index("ix_sync_runs_mode", table_name="sync_runs")
    op.drop_table("sync_runs")

    # Drop the enum types last (PostgreSQL leaves them otherwise; no-op elsewhere).
    bind = op.get_bind()
    sync_run_status.drop(bind, checkfirst=True)
    sync_mode.drop(bind, checkfirst=True)
    closure_reason.drop(bind, checkfirst=True)
    job_status.drop(bind, checkfirst=True)
